apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: "2021-04-28T02:00:09Z"
  labels:
    controller-uid: 40d01bea-e4cb-4a2d-9681-4aa9665d7c33
    job-name: op-extdicts-filler-1619575200
  name: op-extdicts-filler-1619575200
  namespace: agc-dev
  ownerReferences:
  - apiVersion: batch/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: CronJob
    name: op-extdicts-filler
    uid: 4de126bb-3415-433a-9461-7ae3412b77a8
  resourceVersion: "65346960"
  selfLink: /apis/batch/v1/namespaces/agc-dev/jobs/op-extdicts-filler-1619575200
  uid: 40d01bea-e4cb-4a2d-9681-4aa9665d7c33
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 40d01bea-e4cb-4a2d-9681-4aa9665d7c33
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: 40d01bea-e4cb-4a2d-9681-4aa9665d7c33
        job-name: op-extdicts-filler-1619575200
    spec:
      containers:
      - env:
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              key: pg_password
              name: op-extdicts-filler
        - name: ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: access_key
              name: op-extdicts-filler
        image: docker-tlp.local.profee.com/op-extdicts-filler:TIM-2635-Add-schema-external_dicts-to-AGC_48d5878
        imagePullPolicy: IfNotPresent
        name: op-extdicts-filler
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 192Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/config.yaml
          name: configfile
          subPath: config.yaml
      dnsPolicy: ClusterFirst
      nodeSelector:
        node-role.kubernetes.io/worker: worker
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: op-extdicts-filler
        name: configfile
status:
  completionTime: "2021-04-28T02:00:13Z"
  conditions:
  - lastProbeTime: "2021-04-28T02:00:13Z"
    lastTransitionTime: "2021-04-28T02:00:13Z"
    status: "True"
    type: Complete
  startTime: "2021-04-28T02:00:09Z"
  succeeded: 1
